message_id: 746747294438916170

mandatory_roles:
  ps2_logo: planetside
  
roles:
  squad_logo: squad
  eft_logo: tarkov
  warthunder_logo: warthunder
  starcitizen_logo: starcitizen

welcome_message: please state your business
followup_message: An <@&712756833957183518> will be with you as soon as possible
